### ISSUE TITLE
SIGSEGV in case of invalid currency server

### ISSUE THREAD

**Issue by moteus** [prebid/prebid-server#1136]
```
 E1206 13:50:19.958735    7353 rate_converter.go:114] Error updating conversion rates: Get : unsupported protocol scheme ""
 E1206 13:50:19.981677    7353 facebook.go:411] No facebook partnerID specified. Calls to the Audience Network will fail. Did you set adapters.facebook.platform_id in the app config?
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8ac7fc]
 
 goroutine 1 [running]:
 github.com/prebid/prebid-server/currencies.(*RateConverter).GetInfo(0xc0000eefc0, 0x0, 0x0)
     /tmp/prebid-server/currencies/rate_converter.go:179 +0xac
 github.com/prebid/prebid-server/endpoints.newCurrencyRatesInfo(0xdcaea0, 0xc0000eefc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
     /tmp/prebid-server/endpoints/currency_rates.go:39 +0x96
 github.com/prebid/prebid-server/endpoints.NewCurrencyRatesEndpoint(0xdcaea0, 0xc0000eefc0, 0x12)
     /tmp/prebid-server/endpoints/currency_rates.go:61 +0x4d
 github.com/prebid/prebid-server/router.Admin(0x0, 0x0, 0xc0000eefc0, 0xc0002fc080)
     /tmp/prebid-server/router/admin.go:22 +0x17c
 main.serve(0x0, 0x0, 0xc000292a00, 0x0, 0x0)
     /tmp/prebid-server/main.go:63 +0x16a
 main.main()
     /tmp/prebid-server/main.go:39 +0x11c
```
The problem in [the line](https://github.com/prebid/prebid-server/blob/master/currencies/rate_converter.go#L179) `rc.Rates().GetRates()`.
Function `rc.Rates()` may returns nil so there need to add check for it

**Comment by benjaminch** [comment]
Hello @moteus !

Thanks for reporting this one, just push a patch aiming to fix this.

Cheers !
