### ISSUE TITLE
appnexus adapter segfault

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#134]
Seen while running in production on version `0.1.0` with the following stack trace:

```
panic: runtime error: index out of range

goroutine 755733804 [running]:
github.com/prebid/prebid-server/adapters.(*AppNexusAdapter).Call(0xc460655300, 0xc74de0, 0xc479016d20, 0xc498c4c700, 0xc4897e9c00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/dbemiller/go/src/github.com/prebid/prebid-server/adapters/appnexus.go:90 +0xc60
main.auction.func1(0xc75fa0, 0xc460655300, 0xc74de0, 0xc479016d20, 0xc498c4c700, 0xc46052bf00, 0xc42012ac00, 0xc420207040, 0xc479016f60, 0xc4897e9c00)
        /Users/dbemiller/go/src/github.com/prebid/prebid-server/pbs_light.go:312 +0xa0
created by main.auction
        /Users/dbemiller/go/src/github.com/prebid/prebid-server/pbs_light.go:351 +0x6bb
```

This seems to happen _very_ rarely... but should still be fixed.

**Comment by dbemiller** [comment]
These should be gone now... fixed by #400
