### ISSUE TITLE
Interstitial question

### ISSUE THREAD

**Issue by KushnerykPavel** [prebid/prebid-server#2267]
Hello, I received the next error from prebid server. 
`Jun  7 08:26:54 s3036 sleepservice[3695232]: 2022/06/07 08:26:54 http: panic serving 127.0.0.1:42066: runtime error: invalid memory address or nil pointer dereference
Jun  7 08:26:54 s3036 sleepservice[3695232]: goroutine 9565 [running]:
Jun  7 08:26:54 s3036 sleepservice[3695232]: net/http.(*conn).serve.func1(0xc006b83040)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/net/http/server.go:1800 +0x139
Jun  7 08:26:54 s3036 sleepservice[3695232]: panic(0xd9f420, 0x16cecf0)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/runtime/panic.go:975 +0x3e3
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/prebid/prebid-server/endpoints/openrtb2.processInterstitials(0xc0068fb180, 0xc005ecac00, 0xc0067a8b40)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/var/src/github.com/prebid/prebid-server/endpoints/openrtb2/interstitial.go:28 +0x113
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/prebid/prebid-server/endpoints/openrtb2.(*endpointDeps).parseRequest(0xc0004462d0, 0xc005ecac00, 0xc0068fb180, 0xc005e62ab0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/var/src/github.com/prebid/prebid-server/endpoints/openrtb2/auction.go:315 +0x629
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/prebid/prebid-server/endpoints/openrtb2.(*endpointDeps).Auction(0xc0004462d0, 0x104e820, 0xc00506f340, 0xc005ecac00, 0x0, 0x0, 0x0)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/var/src/github.com/prebid/prebid-server/endpoints/openrtb2/auction.go:154 +0x37a
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00010e480, 0x104e820, 0xc00506f340, 0xc005ecac00)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/root/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc37
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/rs/cors.(*Cors).Handler.func1(0x104e820, 0xc00506f340, 0xc005ecac00)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/root/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1bb
Jun  7 08:26:54 s3036 sleepservice[3695232]: net/http.HandlerFunc.ServeHTTP(0xc0035fb0c0, 0x104e820, 0xc00506f340, 0xc005ecac00)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/net/http/server.go:2041 +0x44
Jun  7 08:26:54 s3036 sleepservice[3695232]: github.com/prebid/prebid-server/router.NoCache.ServeHTTP(0x103d9c0, 0xc0035fb0c0, 0x104e820, 0xc00506f340, 0xc005ecac00)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/var/src/github.com/prebid/prebid-server/router/router.go:104 +0x22e
Jun  7 08:26:54 s3036 sleepservice[3695232]: net/http.serverHandler.ServeHTTP(0xc0005bce00, 0x104e820, 0xc00506f340, 0xc005ecac00)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/net/http/server.go:2836 +0xa3
Jun  7 08:26:54 s3036 sleepservice[3695232]: net/http.(*conn).serve(0xc006b83040, 0x10524e0, 0xc006044100)
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/net/http/server.go:1924 +0x86c
Jun  7 08:26:54 s3036 sleepservice[3695232]: created by net/http.(*Server).Serve
Jun  7 08:26:54 s3036 sleepservice[3695232]: #011/usr/local/go/src/net/http/server.go:2962 +0x35c
`

Am I need to check nil in here ? 
https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/interstitial.go#L27

Because function (de *DeviceExt) GetPrebid() can return nil.
https://github.com/prebid/prebid-server/blob/be2dc1c344bec1083647306fc2e75e2e5fb7a1c9/openrtb_ext/request_wrapper.go#L602

**Comment by bretg** [comment]
What's the input that's causing this @KushnerykPavel ?

**Comment by KushnerykPavel** [comment]
@mansinahar @bretg May I fix it ?

**Comment by AlexBVolcy** [comment]
A small typo/bug was discovered while looking into this question. A PR for a fix to this is at this PR: https://github.com/prebid/prebid-server/pull/2275
