### ISSUE TITLE
Panics from the GDPR code

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#588]
I'm seeing a few panics in the app logs from the GDPR code:

```
2018/06/27 03:55:23 http: panic serving 172.16.30.0:34868: runtime error: index out of range
goroutine 37531877 [running]:
net/http.(*conn).serve.func1(0xc44cc3bd60)
        /path/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x987dc0, 0xdcdde0)
        /path/go-1.10/src/runtime/panic.go:505 +0x229
github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent.isSet(...)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent/consent.go:93
github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent.parseException(0xc448839540, 0x4b, 0x4b, 0x258, 0xab7480, 0xc44d04913c, 0x11, 0x0, 0x0)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent/rangesection.go:51 +0x953
github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent.parseRangeSection(0xc448839540, 0x4b, 0x4b, 0xc448839540, 0x4b, 0x4b)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent/rangesection.go:21 +0x139
github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent.Parse(0xc448839540, 0x4b, 0x4b, 0xc448839540, 0x4b, 0x4b, 0x0)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent/consent.go:83 +0x94
github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent.ParseString(0xc4443607cd, 0x64, 0xc45d7976b8, 0xc45d52f2c0, 0x0, 0x1)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/prebid/go-gdpr/vendorconsent/consent.go:70 +0x92
github.com/prebid/prebid-server/gdpr.(*permissionsImpl).allowSync(0xc441e18060, 0xabc2e0, 0xc4200be020, 0x20, 0xc4443607cd, 0x64, 0x40aa60, 0xc4443607c0, 0xa3d9d1)
        /path/src/github.com/prebid/prebid-server/gdpr/impl.go:47 +0x48
github.com/prebid/prebid-server/gdpr.(*permissionsImpl).HostCookiesAllowed(0xc441e18060, 0xabc2e0, 0xc4200be020, 0xc4443607cd, 0x64, 0xc45d797628, 0xc45d797600, 0x0)
        /path/src/github.com/prebid/prebid-server/gdpr/impl.go:25 +0x5b
github.com/prebid/prebid-server/endpoints.preventSyncsGDPR(0x0, 0x0, 0xc4443607cd, 0x64, 0xab8de0, 0xc441e18060, 0xa6b4f0, 0xc44f4eaad0, 0x18, 0xc44f4eaac0)
        /path/src/github.com/prebid/prebid-server/endpoints/setuid.go:93 +0x6f
github.com/prebid/prebid-server/endpoints.NewSetUIDEndpoint.func1(0xabbe60, 0xc4624eca80, 0xc45a881e00, 0x0, 0x0, 0x0)
        /path/src/github.com/prebid/prebid-server/endpoints/setuid.go:37 +0x271
github.com/prebid/prebid-server/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4202d7ce0, 0xabbe60, 0xc4624eca80, 0xc45a881e00)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6c1
github.com/prebid/prebid-server/vendor/github.com/rs/cors.(*Cors).Handler.func1(0xabbe60, 0xc4624eca80, 0xc45a881e00)
        /path/src/github.com/prebid/prebid-server/vendor/github.com/rs/cors/cors.go:200 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc441e05f20, 0xabbe60, 0xc4624eca80, 0xc45a881e00)
        /path/go-1.10/src/net/http/server.go:1947 +0x44
main.NoCache.ServeHTTP(0xab77a0, 0xc441e05f20, 0xabbe60, 0xc4624eca80, 0xc45a881e00)
        /path/src/github.com/prebid/prebid-server/pbs_light.go:579 +0x137
net/http.serverHandler.ServeHTTP(0xc440768410, 0xabbe60, 0xc4624eca80, 0xc45a881e00)
        /path/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc44cc3bd60, 0xabc2a0, 0xc451bce740)
        /path/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /path/go-1.10/src/net/http/server.go:2795 +0x27b
2018/06/27 03:55:23 http: panic serving 172.16.41.0:37432: runtime error: index out of range
```

Need to investigate. Not sure if this is a bug in PBS, or the go-gdpr library.

**Comment by dbemiller** [comment]
Tracked this back to a bug in the `go-gdpr` parsing library: https://github.com/prebid/go-gdpr/issues/10

Closing this, since it's not a PBS issue.
